version: "3.8"
services:
    lldqn:
        container_name: lldqn-deps
        image: aleksasukovic/lldqn:gradient
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8888:8888
        volumes:
            - .:/home/app
        command: tail -f /dev/null
