name: lifelong_learning_project
channels:
    - defaults
    - pytorch
    - conda-forge
    - cogsci
dependencies:
    - python=3.9
    - numpy=1.19.*
    - ipykernel=6.9.*
    - jupyterhub=2.3.*
    - jupyterlab=3.3.*
    - matplotlib=3.5.*
    - numba=0.55.*
    - pandas=1.4.*
    - pip=21.2.*
    - scikit-learn=1.0.*
    - scipy=1.6.*
    - pytorch=1.7.*
    - torchvision=0.8.*
    - pybox2d=2.3.*
    - pytest=7.1.*
    - tensorboard=2.4.*
    - tensorflow=2.4.*
    - tqdm=4.64.*
    - pyglet=1.5.*
    - xlrd=2.0.*
    - seaborn=0.11.*
    - wandb=0.12.*
    - pip:
        - gym==0.23.*
        - pygame==2.1.*
